### ISSUE TITLE
Error when reopening the opened topic

### ISSUE THREAD

**Issue by slaweally** [mentionbb/mentionbb#12]
### Which MentionBB version?

Version: 1.0.21, Build 11021000

### Description

It gives an error when we reopen the opened topic, when we want to open a new topic and read the topic, it gives an error like the image below. even if we reload, it stays the same. there is no problem in opening other topics, we only received an error in this way in the newly opened topic. there is no problem when re-reading open topics.

<img width="1065" alt="Ekran Resmi 2024-12-22 22 39 18" src="https://github.com/user-attachments/assets/3a8fb994-5551-431e-b836-53d973f723a1" />

**Comment by par274** [comment]
Dom problem again. I hope last bug 😆 

Fixed b57619e8198b9edf801a8a109f227f63cb66e5f5
