### ISSUE TITLE
Tools & Contact Notifications not working

### ISSUE THREAD

**Issue by stump9** [mentionbb/mentionbb#2]
Hello, nice forum software here, have installed it on my domain and it's working fine. The issue is that the admin panel "Tools and Contacts, Notifications gives 404..kindly fix that issue. 
Thanks
![Screenshot 2023-02-25 at 09 51 59](https://user-images.githubusercontent.com/126314444/221343267-1350a00d-abfc-494f-9797-2578ba5d4f83.png)

**Comment by par274** [comment]
These pages are still under developer.

**Comment by stump9** [comment]
Sure,but the script is very good..needs little polish.

**Comment by par274** [comment]
> Sure,but the script is very good..needs little polish.

U can write Polish language. Just create new language from Admin panel and then edit language files. Do not edit from admin panel, It's just end-user editing.

When you write the Polish language, I can add it to Github.

**Comment by stump9** [comment]
Sorry, i did not mean "polish" language..i meant it need little fix, and it will be one of the greats forum softwares..using it now for production..and it runs okay.

**Comment by par274** [comment]
> Sorry, i did not mean "polish" language..i meant it need little fix, and it will be one of the greats forum softwares..using it now for production..and it runs okay.

Haha im sorry too. It was a polish & Polish fallacy. 

Thank you for your good wishes, it's still under development.

**Comment by stump9** [comment]
Alright, Thanks for the reply
