### ISSUE TITLE
No issue just some praise!

### ISSUE THREAD

**Issue by WebCrew** [mentionbb/mentionbb#4]
No problem, **just praise**! 

What I can see so far **is really great**, keep at it, it's going to be something really great!

Most of the forums that are still used **relatively often these days** are from the **games industry**, so I would advise you to focus on cool user profile pages and the ability to easily customize the style of the forum. 

**Gamers** want it to **be playful**, with **avatar and header images and a message feed** in the profile, and **game developers** love to be able to **customize forums to their corporate identity**, i.e. their company colors, etc.

I wish you the **best of luck** and that you never get frustrated.

Kind regards, Andy :)

**Comment by par274** [comment]
Thank you for this compliment.

Although the project development is slow, I pay a lot of attention to adding new features, stability and security. The commits I have sent to Github in recent months are especially related to stability and performance.

I will take into consideration what you said about the customizing ui/ux.

**Comment by WebCrew** [comment]
**Stability, performance and security** are **very important** I think it's good **that you value this**. 

Just keep going, everything looks really good so far.
