### ISSUE TITLE
Setup Assistance

### ISSUE THREAD

**Issue by ardaabi1** [mentionbb/mentionbb#8]
I need help with the cPanel installation. Despite following everything in the README, I couldn't complete the installation.

**Comment by par274** [comment]
> I need help with the cPanel installation. Despite following everything in the README, I couldn't complete the installation.

Have you seen an error? If so, share.

**Comment by ardaabi1** [comment]
No, but the page on the site gives a 404 error.

**Comment by par274** [comment]
> No, but the page on the site gives a 404 error.

The home directory must be "public". This may be the problem.

**Comment by ardaabi1** [comment]
As I mentioned, I did everything without any issues, the files are public_html, but it still doesn't work. I'm checking if there's anything I'm missing.

**Comment by par274** [comment]
I don't mean the files are in public_html, if you notice there is a folder named "public" in the root directory. In the hosting settings in Cpanel, you need to make the root directory public_html/public so that it can see the index.php page.

**Comment by ardaabi1** [comment]
I don't know how to make the change, but is this an error and will it be fixed in the future?

**Comment by par274** [comment]
No, this is not a bug/error. It is a result of incorrect routing on the server Apache or Nginx.

However, I must say that I have never tried the project on Cpanel. But theoretically there is no reason why it should not work.

**Comment by ardaabi1** [comment]
Do I need to install Nginx on cPanel?

**Comment by par274** [comment]
> Do I need to install Nginx on cPanel?

No, this is not necessary. It should work fine on Apache as well.

I will try it on Apache right now and write the result here.

**Comment by ardaabi1** [comment]
Got it, I'm waiting.

**Comment by par274** [comment]
> Got it, I'm waiting.

https://mentionbb.com/

Currently running Apache. There is no problem but I still edited .htaccess. I will publish a new release soon, you can download it or copy the htaccess in public directly.

https://github.com/mentionbb/mentionbb/releases/tag/mentionbb-11020000-6
https://github.com/mentionbb/mentionbb/blob/master/public/.htaccess

But as I said, you should make the main directory in Cpanel public_html/public, this is a must.

https://support.cpanel.net/hc/en-us/articles/360057802373-How-can-I-change-the-document-root-for-an-Addon-Domain-or-Subdomain

**Comment by ardaabi1** [comment]
I will contact my provider and ask them to change it, and I will get back to you.

**Comment by ardaabi1** [comment]
Is there any chance you could provide the demo admin account for mentionbb.com? I would like to browse it.

**Comment by par274** [comment]
> Is there any chance you could provide the demo admin account for mentionbb.com? I would like to browse it.

TestUser
123456.,

**Comment by ardaabi1** [comment]
Thank you.

**Comment by ardaabi1** [comment]
In the new version, the DBconfig.php file is not inside the src folder, just so you know.

**Comment by par274** [comment]
> In the new version, the DBconfig.php file is not inside the src folder, just so you know.

The DbConfig.php file is no longer with us. :)

[Env implementation, remove complex DbConfig.php](https://github.com/mentionbb/mentionbb/commit/4e2802f06d36b9fde963caf78ab2ff3ad3427428)
https://github.com/mentionbb/mentionbb/blob/master/.env.example

Readme has already changed for this.

**Comment by ardaabi1** [comment]
Haha, I’m genuinely very happy. Should we create the '.env' file inside the src folder again? I couldn’t fully understand it, and I didn't see it in the 'readme.md'.

**Comment by par274** [comment]
> Haha, I’m genuinely very happy. Should we create the '.env' file inside the src folder again? I couldn’t fully understand it, and I didn't see it in the 'readme.md'.

No, it should be in the main directory.

There are two ways to do this:
You can change the name of the .env.example file to .env and edit it.
Or you can create it automatically with the command line. Editing is often easier.

**Comment by ardaabi1** [comment]
The 'readme.tr-tr.md' hasn't been updated either, so I apologize for that :)

**Comment by par274** [comment]
> The 'readme.tr-tr.md' hasn't been updated either, so I apologize for that :)

Yes, I will edit it soon.

**Comment by ardaabi1** [comment]
Thank you.

**Comment by ardaabi1** [comment]
Let me clarify this topic: the site was not entirely prepared for cPanel but rather for VDS installation. It causes numerous issues in cPanel, such as file detection problems, among others. Therefore, the infrastructure needs a significant review.

**Comment by ardaabi1** [comment]
I successfully completed the installation, but clicking the login button redirects to a 404 page again. I extracted the vendor.zip file and added it to the src folder, but I am not sure if it is functioning properly.

**Comment by par274** [comment]
If the hosting provides the necessary PHP extensions, there is no reason why it shouldn't work. Some hostings disable extensions that XenForo also needs, so the software can't be used.

Unfortunately, I can't test it right now because I don't have Cpanel. If you share the passwords I'd love to take a look.

**Comment by ardaabi1** [comment]
Sure, where can I contact you?

**Comment by par274** [comment]
> Sure, where can I contact you?

parantezprojects@gmail.com You can mail your server details here.

**Comment by ardaabi1** [comment]
I have sent the credentials via email for your information.

**Comment by par274** [comment]
The reason why it doesn't work is obvious, the "site_url" written in the database is https://pixeloyuncu.tr but the address where you actually use the software is https://forum.pixeloyuncu.tr

So I edited it and now it works. :)

**Comment by ardaabi1** [comment]
I am very sorry; it completely slipped my mind. The provider has been very confusing for me. I apologize.

**Comment by par274** [comment]
> I am very sorry; it completely slipped my mind. The provider has been very confusing for me. I apologize.

No problem bro.

Actually this gave me an idea; I will add a module to show a warning if users enter the domain incorrectly.

**Comment by ardaabi1** [comment]
Once again, I apologize. I will test the site and provide my feedback and thoughts to you. Thank you again.

**Comment by par274** [comment]
> Once again, I apologize. I will test the site and provide my feedback and thoughts to you. Thank you again.

As I said, it's not a problem. In fact, it would have been a bigger problem if the software hadn't worked on Cpanel. :D

**Comment by ardaabi1** [comment]
I encountered the following issue: during registration, it asks for reCaptcha, and since it is not integrated into the site, it gives an error and does not complete the registration. In the admin panel, as far as I can see, there is no button to activate or deactivate it, and I couldn't find it in phpMyAdmin either.

**Comment by par274** [comment]
> I encountered the following issue: during registration, it asks for reCaptcha, and since it is not integrated into the site, it gives an error and does not complete the registration. In the admin panel, as far as I can see, there is no button to activate or deactivate it, and I couldn't find it in phpMyAdmin either.

There is actually a option in the admin panel to enter ReCaptcha keys: admin/settings?recaptcha

But there is no close, I need to add this.

**Comment by ardaabi1** [comment]
I should mention that the following features need to be added to the admin panel: Editing the header menu, adding a footer with the ability to edit it, changing the site logo, changing the site title, and other important functionalities. Additionally, the ability to create roles and assign restricted permissions to those roles should be included.

**Comment by par274** [comment]
You can actually edit the site logo and title.

![resim](https://github.com/user-attachments/assets/de3536b8-facf-4ecd-85ca-1719901f858d)
![resim](https://github.com/user-attachments/assets/5c1859f1-8a67-4bf6-824c-22dbf6ed97a6)
